### ISSUE TITLE
Context undefined

### ISSUE THREAD

**Issue by IAmSaeve** [cubbit/enigma#11]
Hi,
I am trying to implement the Enigma module in a simple React project, but I keep getting `TypeError: context is undefined` thrown by the `em_array_malloc` function.

I followed the guide in the readme but can't figure out why context is undefined.

**Comment by marmos91** [comment]
Hi @sebkirller, could you please provide some snippet and your webpack configuration so we can help you out?

**Comment by IAmSaeve** [comment]
Hi @marmos91,
The code I am trying to is:
```js
import Enigma from "@cubbit/enigma";
import { WebFileStream } from '@cubbit/web-file-stream';

function enc(e) {
    e.preventDefault()

    const file = new File(['My test file'], 'test-file.txt', {
      type: 'text/plain'
    });
    const read_stream = WebFileStream.create_read_stream(file);

    new Enigma.AES().init().then((aes) =>
    {
        const iv = Enigma.Random.bytes(16);
        const aes_stream = aes.encrypt_stream(iv);
    
        aes_stream.once('finish', () => console.log('File encrypted'));
    
        read_stream.pipe(aes_stream);
    });
  }
```

As for the webpack config. I just ejected the React project, but that config is a bit too big. Is there any part of the config you're interested in?

**Comment by marmos91** [comment]
You are only missing the `Enigma.init()` call at the start (this call is needed to actually load the WebAssembly in memory).

An async/await version of your code could be:
```ts
  async function enc(e) {
    e.preventDefault();

    await Enigma.init();

    const file = new File(['My test file'], 'test-file.txt', {
      type: 'text/plain'
    });
    const read_stream = WebFileStream.create_read_stream(file);

    const aes = await new Enigma.AES().init();
    const iv = Enigma.Random.bytes(16);
    const aes_stream = aes.encrypt_stream(iv);

    aes_stream.once('finish', () => console.log('File encrypted'));

    read_stream.pipe(aes_stream);
  }
```

Otherwise, with normal promises:
```ts
function enc(e) {
    e.preventDefault();

    Enigma.init().then(() => {
      const file = new File(['My test file'], 'test-file.txt', {
        type: 'text/plain'
      });
      const read_stream = WebFileStream.create_read_stream(file);
  
      new Enigma.AES().init().then((aes) => {
        const iv = Enigma.Random.bytes(16);
        const aes_stream = aes.encrypt_stream(iv);
    
        aes_stream.once('finish', () => console.log('File encrypted'));
    
        read_stream.pipe(aes_stream);
      });
    });
  }
```

**Comment by IAmSaeve** [comment]
Oh snap you're right!
Maybe the readme should be updated to make this easier for newbies 🤔?
They all use the same `new Enigma.AES().init().then((aes) => {...});` structure without a `Enigma.init()` first.

**Comment by marmos91** [comment]
Thanks for the the feedback, we are going to update the README 😉
