### ISSUE TITLE
WASM in Enigma

### ISSUE THREAD

**Issue by mvpatel2000** [cubbit/enigma#16]
Where exactly is WASM used in this library? The description says "In a web environment, Enigma leverages on a WebAssembly-compiled version of OpenSSL to boost performances." but it seems to me it is just using Web Crypto?

**Comment by alessiopcc** [comment]
Hi @mvpatel2000,
it wraps Web Crypto for basic algorithms but it leverages on WASM for more intensive operations like encrypting/hashing a whole file as a stream.
Through WASM it also provides algorithms not supported by Web Crypto like ED25519.

**Comment by mvpatel2000** [comment]
Thanks. So to confirm, for RSA, there is no use of WASM?

**Comment by alessiopcc** [comment]
Yes, actually RSA only uses Web Crypto
